import { Transaction, RecurringExpense, SavingsGoal, BankAccountDetails, UpcomingPayment } from '../types/finance';

export const EXISTING_ADMIN_PHONE = '7702994407';

export const EXISTING_USER_BANK_ACCOUNTS: BankAccountDetails[] = [
  {
    id: 'acc-hdfc-01',
    bankName: 'HDFC Bank',
    accountNumberMasked: '•••• 4821',
    accountNumberLast4: '4821',
    accountType: 'Salary',
    balance: 50000,
    nickname: 'Primary Salary',
    isPrimary: true,
  },
  {
    id: 'acc-sbi-02',
    bankName: 'State Bank of India',
    accountNumberMasked: '•••• 1934',
    accountNumberLast4: '1934',
    accountType: 'Savings',
    balance: 25000,
    nickname: 'Emergency & Savings',
    isPrimary: false,
  },
  {
    id: 'acc-cash-03',
    bankName: 'Cash In Hand',
    accountNumberMasked: '•••• CASH',
    accountNumberLast4: 'CASH',
    accountType: 'Savings',
    balance: 3400,
    nickname: 'Daily Pocket Cash',
    isPrimary: false,
  },
];

export function getExistingUserTransactions(monthKey?: string): Transaction[] {
  const now = new Date();
  const y = now.getFullYear();
  const m = (now.getMonth() + 1).toString().padStart(2, '0');
  const targetMonth = monthKey || `${y}-${m}`;

  return [
    {
      id: 'tx-afzal-01',
      date: `${targetMonth}-01`,
      merchant: 'TCS / Tech Corp Payroll',
      amount: 75000,
      type: 'income',
      categoryId: 'cat-income-salary',
      paymentMethod: 'net_banking',
      accountId: 'acc-hdfc-01',
      notes: 'Monthly Net Take-Home Salary credited',
    },
    {
      id: 'tx-afzal-02',
      date: `${targetMonth}-03`,
      merchant: 'FinTech UI Consulting',
      amount: 1650,
      type: 'income',
      categoryId: 'cat-income-freelance',
      paymentMethod: 'upi',
      accountId: 'acc-sbi-02',
      notes: 'Advisory retainer payment',
    },
    {
      id: 'tx-afzal-03',
      date: `${targetMonth}-05`,
      merchant: 'Landlord / Apartment Rent',
      amount: 18000,
      type: 'expense',
      categoryId: 'cat-housing',
      paymentMethod: 'net_banking',
      accountId: 'acc-hdfc-01',
      notes: '2BHK Apartment Monthly Rent (HDFC IMPS)',
    },
    {
      id: 'tx-afzal-04',
      date: `${targetMonth}-07`,
      merchant: 'Zerodha Coin / Nifty 50 Index',
      amount: 10000,
      type: 'expense',
      categoryId: 'cat-investments',
      paymentMethod: 'net_banking',
      accountId: 'acc-hdfc-01',
      notes: 'Monthly Automated SIP Mutual Fund Allocation',
    },
    {
      id: 'tx-afzal-05',
      date: `${targetMonth}-08`,
      merchant: 'Blinkit Superstore',
      amount: 3850,
      type: 'expense',
      categoryId: 'cat-groceries',
      paymentMethod: 'upi',
      accountId: 'acc-hdfc-01',
      notes: 'Monthly staples, dry fruits, fresh produce',
    },
    {
      id: 'tx-afzal-06',
      date: `${targetMonth}-10`,
      merchant: 'TSSPDCL Power Distribution',
      amount: 2450,
      type: 'expense',
      categoryId: 'cat-utilities',
      paymentMethod: 'upi',
      accountId: 'acc-hdfc-01',
      notes: 'Electricity bill payment for current billing cycle',
    },
    {
      id: 'tx-afzal-07',
      date: `${targetMonth}-12`,
      merchant: 'Airtel Xstream Fibernet',
      amount: 1179,
      type: 'expense',
      categoryId: 'cat-utilities',
      paymentMethod: 'upi',
      accountId: 'acc-hdfc-01',
      notes: 'High-speed broadband monthly subscription with GST',
    },
    {
      id: 'tx-afzal-08',
      date: `${targetMonth}-14`,
      merchant: 'Shell India Fuel Station',
      amount: 1800,
      type: 'expense',
      categoryId: 'cat-transport',
      paymentMethod: 'credit_card',
      accountId: 'acc-hdfc-01',
      notes: 'Vehicle petrol tank full recharge',
    },
    {
      id: 'tx-afzal-09',
      date: `${targetMonth}-16`,
      merchant: 'Swiggy / Biryani House',
      amount: 650,
      type: 'expense',
      categoryId: 'cat-dining',
      paymentMethod: 'upi',
      accountId: 'acc-hdfc-01',
      notes: 'Weekend dinner order for family',
    },
    {
      id: 'tx-afzal-10',
      date: `${targetMonth}-18`,
      merchant: 'Apollo Pharmacy & Wellness',
      amount: 640,
      type: 'expense',
      categoryId: 'cat-health',
      paymentMethod: 'cash',
      accountId: 'acc-cash-03',
      notes: 'Monthly multivitamin and healthcare supplies',
    },
    {
      id: 'tx-afzal-11',
      date: `${targetMonth}-20`,
      merchant: 'Netflix India Premium',
      amount: 649,
      type: 'expense',
      categoryId: 'cat-entertainment',
      paymentMethod: 'credit_card',
      accountId: 'acc-hdfc-01',
      notes: '4K Ultra HD monthly streaming plan',
    },
    {
      id: 'tx-afzal-12',
      date: `${targetMonth}-22`,
      merchant: 'Myntra Fashion',
      amount: 2500,
      type: 'expense',
      categoryId: 'cat-shopping',
      paymentMethod: 'credit_card',
      accountId: 'acc-hdfc-01',
      notes: 'Work wear & casual sneakers',
    },
    {
      id: 'tx-afzal-13',
      date: `${targetMonth}-24`,
      merchant: 'Barbeque Nation Dining',
      amount: 1420,
      type: 'expense',
      categoryId: 'cat-dining',
      paymentMethod: 'upi',
      accountId: 'acc-hdfc-01',
      notes: 'Team celebration dinner buffet',
    },
    {
      id: 'tx-afzal-14',
      date: `${targetMonth}-26`,
      merchant: 'Third Wave Coffee Roasters',
      amount: 480,
      type: 'expense',
      categoryId: 'cat-dining',
      paymentMethod: 'cash',
      accountId: 'acc-cash-03',
      notes: 'Artisan cold brew and bakery snack',
    },
  ];
}

export const EXISTING_USER_RECURRING: RecurringExpense[] = [
  {
    id: 'rec-01',
    name: 'Apartment Rent',
    merchant: 'Apartment Rent',
    amount: 18000,
    categoryId: 'cat-housing',
    billingCycle: 'monthly',
    nextDueDate: '2026-10-05',
    status: 'active',
    utility: 'essential',
    description: 'Primary residential rent',
  },
  {
    id: 'rec-02',
    name: 'Zerodha Index Fund SIP',
    merchant: 'Zerodha Index Fund SIP',
    amount: 10000,
    categoryId: 'cat-investments',
    billingCycle: 'monthly',
    nextDueDate: '2026-10-07',
    status: 'active',
    utility: 'essential',
    description: 'Disciplined wealth building',
  },
  {
    id: 'rec-03',
    name: 'TSSPDCL Electricity Board',
    merchant: 'TSSPDCL Electricity Board',
    amount: 2450,
    categoryId: 'cat-utilities',
    billingCycle: 'monthly',
    nextDueDate: '2026-10-10',
    status: 'active',
    utility: 'essential',
    description: 'Power utility bill',
  },
  {
    id: 'rec-04',
    name: 'Airtel Xstream Fibernet',
    merchant: 'Airtel Xstream Fibernet',
    amount: 1179,
    categoryId: 'cat-utilities',
    billingCycle: 'monthly',
    nextDueDate: '2026-10-12',
    status: 'active',
    utility: 'essential',
    description: 'High speed work from home internet',
  },
  {
    id: 'rec-05',
    name: 'Netflix Premium 4K',
    merchant: 'Netflix Premium 4K',
    amount: 649,
    categoryId: 'cat-entertainment',
    billingCycle: 'monthly',
    nextDueDate: '2026-10-20',
    status: 'active',
    utility: 'useful',
    description: 'Family entertainment',
  },
];

export const EXISTING_USER_GOALS: SavingsGoal[] = [
  {
    id: 'goal-01',
    name: 'Emergency Reserve Fund (6 Months)',
    targetAmount: 150000,
    currentAmount: 75000,
    targetDate: '2027-03-31',
    category: 'Emergency',
    color: '#10b981',
    emoji: '🛡️',
  },
  {
    id: 'goal-02',
    name: 'Workstation Tech Hardware Upgrade',
    targetAmount: 80000,
    currentAmount: 45000,
    targetDate: '2026-12-31',
    category: 'Gadgets & Tech',
    color: '#6366f1',
    emoji: '💻',
  },
];

export const EXISTING_USER_UPCOMING: UpcomingPayment[] = [
  {
    id: 'upc-01',
    name: 'Apartment Rent',
    amount: 18000,
    categoryId: 'cat-housing',
    dueDate: '2026-10-05',
    status: 'completed',
    autoPayEnabled: true,
    notes: 'Landlord Transfer',
  },
  {
    id: 'upc-02',
    name: 'Monthly SIP Investment',
    amount: 10000,
    categoryId: 'cat-investments',
    dueDate: '2026-10-07',
    status: 'completed',
    autoPayEnabled: true,
    notes: 'Zerodha Coin',
  },
  {
    id: 'upc-03',
    name: 'Electricity Bill TSSPDCL',
    amount: 2450,
    categoryId: 'cat-utilities',
    dueDate: '2026-10-10',
    status: 'completed',
    autoPayEnabled: true,
    notes: 'TSSPDCL',
  },
  {
    id: 'upc-04',
    name: 'Airtel Broadband',
    amount: 1179,
    categoryId: 'cat-utilities',
    dueDate: '2026-10-12',
    status: 'completed',
    autoPayEnabled: true,
    notes: 'Airtel Fibernet',
  },
  {
    id: 'upc-05',
    name: 'Netflix Premium',
    amount: 649,
    categoryId: 'cat-entertainment',
    dueDate: '2026-10-20',
    status: 'completed',
    autoPayEnabled: false,
    notes: 'Netflix',
  },
];
